environments:
  - name: dev
    dockerfile: Dockerfile.dev
    tag: myapp-dev
  - name: qa
    dockerfile: Dockerfile.qa
    tag: myapp-qa
  - name: prod
    dockerfile: Dockerfile.prod
    tag: myapp-prod
