images:
  - name: app-dev
    dockerfile: Dockerfile.dev
    tag: myapp-dev:latest
  - name: app-qa
    dockerfile: Dockerfile.qa
    tag: myapp-qa:latest
  - name: app-prod
    dockerfile: Dockerfile.prod
    tag: myapp-prod:latest
