images:
  - name: app-dev
    dockerfile: ./dockerfile/Dockerfile.dev
    tag: myapp-dev:latest
  - name: app-qa
    dockerfile: ./dockerfile/Dockerfile.qa
    tag: myapp-qa:latest
  - name: app-prod
    dockerfile: ./dockerfile/Dockerfile.prod
    tag: myapp-prod:latest
