name: Docker Build Reusable Workflow

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: true
        type: string
      custom_command:
        required: false  # This is optional
        type: string
        default: "echo No custom command provided"
    # secrets:
    #   TAG:
    #     required: true

jobs:
  docker-build:
    runs-on: self-hosted  # Define the runner in the reusable workflow itself
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ inputs.image_name }}:${{ inputs.tag }} .
      - name: Execute custom command
        run: ${{ inputs.custom_command }}    
