name: Build Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: self-hosted

    strategy:
      matrix:
        dockerfile: 
          - Dockerfile.dev
          - Dockerfile.qa
          - Dockerfile.prod
        context:
          - ./dev
          - ./qa
          - ./prod
        tag: 
          - dev
          - qa
          - prod

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # # Log in to DockerHub (optional, if pushing to DockerHub or any registry)
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker images for each Dockerfile
      - name: Build and push Docker image
        run: |
          echo "Building Docker image using ${{ matrix.dockerfile }}"
          docker build -t myrepo/myimage:${{ matrix.tag }} -f ${{ matrix.dockerfile }} ${{ matrix.context }}
          docker image ls
