name: Build Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  parse-config:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse docker-config.yaml
        id: parse-config
        run: |
          matrix=$(yq eval -o=json '.images' docker-config.yaml | jq -c '.')
          if [[ -z "$matrix" ]]; then
            echo "Error: Matrix is empty. Check docker-config.yaml."
            exit 1
          fi
          echo "Matrix JSON: $matrix" # Debugging output
          printf "matrix=%s\n" "$matrix" >> "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT 
  docker-build:
    needs: parse-config
    runs-on: self-hosted
    strategy:
      matrix:
        image: ${{ fromJSON(needs.parse-config.outputs.matrix) }}
    steps:
      - name: Log Parsed Matrix
        run: |
          echo "Parsed Matrix: ${{ needs.parse-config.outputs.matrix }}"

      # - name: Log the current build
      #   run: |
      #     echo "Building image: ${{ matrix.image.name }}"
      #     echo "Using Dockerfile: ${{ matrix.image.dockerfile }}"
      #     echo "Tagging with: ${{ matrix.image.tag }}"

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ matrix.image.tag }} -f ${{ matrix.image.dockerfile }} .
