# File: .github/workflows/CommonDockerBuild.yml

name: Common Docker Build

on:
  workflow_call:  # This allows other workflows to call this workflow

jobs:
  docker-build:
    runs-on: self-hosted

    # Optionally, you can define inputs for the reusable workflow
    inputs:
      image_name:
        description: 'The name of the Docker image'
        required: true
      tag:
        description: 'The Docker image tag'
        required: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Docker Build
        run: |
          echo "Building Docker image"
          ls
          docker build -t ${{ inputs.image_name }}:${{ inputs.tag }} .
