name: Docker Build Reusable Workflow

on:
  push:
    branches: main
  # workflow_call:
    # inputs:
    #   image_name:
    #     required: true
    #     type: string
    #   tag:
    #     required: false
    #     type: string
    #     default: "latest"
    #   custom_command:
    #     required: false
    #     type: string
    #     default: "echo No custom command provided"

jobs:
  docker-build:
    runs-on: self-hosted

    strategy:
      matrix:
        environment: [dev, qa, prod]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set environment variables
        env:
          IMAGE_NAME: my-docker-repo/my-app  # Replace with your image name
          TAG: latest   

      - name: Build Docker image
        run: |
          echo "Building Docker image for ${{ matrix.environment }} environment..."
          docker build -t ${{ matrix.environment }}-${{ env.TAG }} .

      # - name: Execute custom command
      #   run: ${{ inputs.custom_command }}
  
