name: Hello World Workflow

# This specifies the event that will trigger the workflow
on:
  push:
    branches:
      - main  # This runs the workflow on every push to the "main" branch

# Define the jobs that will run as part of the workflow
jobs:
  say-hello:
    # Runs this job on a self-hosted runner
    runs-on: docker-build

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
      # Print "Hello World" to the console
      - name: Say Hello
        run: echo "Hello, World from a self-hosted runner!"
