name: Build Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  parse-config:
    name: Parse Configuration
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Parse docker-config.yaml
        id: parse-config
        run: |
          config=$(cat docker-config.yaml | yq -o=json)
          matrix=$(echo $config | jq -c '.environments')
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
          echo "helloworld" > $GITHUB_OUTPUT
          echo $GITHUB_OUTPUT

  docker-build:
    needs: parse-config
    runs-on: self-hosted
    strategy:
      matrix:
        config: ${{ fromJson(needs.parse-config.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and Tag Docker Image
        run: |
          echo "Tag: ${{ matrix.config.tag }}"
          echo "Dockerfile: ${{ matrix.config.dockerfile }}"
          docker build -t ${{ matrix.config.tag }} -f ${{ matrix.config.dockerfile }} .
