name: Build Multiple Docker Images

on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: self-hosted
    strategy:
      matrix:
        image: # Define a matrix for multiple images
          - name: app-dev
            dockerfile: Dockerfile.dev
            tag: myapp-dev:latest
          - name: app-qa
            dockerfile: Dockerfile.qa
            tag: myapp-qa:latest
          - name: app-prod
            dockerfile: Dockerfile.prod
            tag: myapp-prod:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log the current build
        run: |
          echo "Building image: ${{ matrix.image.name }}"
          echo "Using Dockerfile: ${{ matrix.image.dockerfile }}"
          echo "Tagging with: ${{ matrix.image.tag }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ matrix.image.tag }} -f ${{ matrix.image.dockerfile }} .

      # - name: Push Docker image to registry (Optional)
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      #     docker push ${{ matrix.image.tag }}
