jobs:
  parse-config:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Parse docker-config.json
        id: parse-config
        run: |
          matrix=$(jq -c '.images' docker-config.json)
          printf "matrix=%s\n" "$matrix" >> "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT

  docker-build:
    needs: parse-config
    runs-on: self-hosted
    strategy:
      matrix: 
        image: ${{ fromJson(needs.parse-config.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log the current build
        run: |
          echo "Building image: ${{ matrix.name }}"
          echo "Using Dockerfile: ${{ matrix.dockerfile }}"
          echo "Tagging with: ${{ matrix.tag }}"

      # - name: Build Docker image
      #   run: |
      #     docker build -t ${{ matrix.tag }} -f ${{ matrix.dockerfile }} .
